# _push_update.ps1 — Publish an update to GitHub for auto-updater delivery
#
# USAGE:
#   1. Build and sign the MSI:        .\  _full_rebuild.ps1
#   2. Upload the MSI to GitHub:      go to https://github.com/MasterShadex/Masters-FM/releases/new
#                                     tag: v<version>  (e.g. v10.1.0)
#                                     upload:  Masters-FM-V<version>.msi
#   3. Run this script:               .\  _push_update.ps1
#
# What this script does:
#   - Reads version.json generated by _full_rebuild.ps1
#   - Sets autoInstall = true  (triggers silent background install for friends)
#   - Commits version.json to git
#   - Pushes to GitHub (origin/main)
#
# To push WITHOUT enabling autoInstall (notify-only mode), run:
#   .\  _push_update.ps1 -NoAutoInstall
#
param(
    [switch]$NoAutoInstall
)

Set-Location "G:\Project Folder\Master FM"
$root            = "G:\Project Folder\Master FM"
$versionJsonPath = Join-Path $root 'version.json'

Write-Host "=== _push_update.ps1 ===" -ForegroundColor Cyan

# Read version.json
if (-not (Test-Path $versionJsonPath)) {
    Write-Host "ERROR: version.json not found at $versionJsonPath" -ForegroundColor Red
    Write-Host "       Run _full_rebuild.ps1 first to generate it." -ForegroundColor Red
    exit 1
}

$json = Get-Content $versionJsonPath -Raw | ConvertFrom-Json
Write-Host "  version:    $($json.version)"
Write-Host "  msi_url:    $($json.msi_url)"
Write-Host "  msi_sha256: $($json.msi_sha256)"
Write-Host "  autoInstall (current): $($json.autoInstall)"

# Flip autoInstall
if ($NoAutoInstall) {
    Write-Host "  -NoAutoInstall flag: keeping autoInstall=false (notify-only)" -ForegroundColor Yellow
    $json.autoInstall = $false
} else {
    Write-Host "  Setting autoInstall=true (friends will auto-download+install)" -ForegroundColor Green
    $json.autoInstall = $true
}

# Write back
$updated = $json | ConvertTo-Json -Compress
[System.IO.File]::WriteAllText($versionJsonPath, $updated, [System.Text.Encoding]::UTF8)
Write-Host "  version.json updated."

# Git commit + push
Write-Host ""
Write-Host "Committing and pushing..." -ForegroundColor Cyan
$ver = $json.version

git add version.json
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: git add failed" -ForegroundColor Red; exit 2 }

git commit -m "release v$ver"
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: git commit failed" -ForegroundColor Red; exit 3 }

git push origin main
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: git push failed" -ForegroundColor Red; exit 4 }

Write-Host ""
Write-Host "=== DONE: v$ver published. Friends will update within 6 hours. ===" -ForegroundColor Green
